language: java
jdk:
- oraclejdk8
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
after_success:
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
env:
  global:
  - secure: PIbHGVr+Bv0HbK6qOE6C0FrVqcsm/Q6kzFCOa4y9ixT8+2i82DDP4kyyy2ymKevmps+7+SCeJiW8KQkZa7gztSG0h1BoHJo0C6f0xiMYG4kY/7Gq4ZX3mehOVFUymxqhVED/NMK4a7JJxqcSH7JIkBLkuEaueqxc3CmHjI7LCqTr9yMdu/8ulhOeEL/Drg0zsNK9424K6BtxnTh6nNmbNfRnvxCgFc3mLuZ4J6/YN7lBagNiBhpr3XsXdvUC/W89UCcQCIkl/xBKPTxoUGxD6YG+IhapEJrQvqsFkvwFcsUUa9iL7+23QDlK7VGXeKZxwcMYWjRSVai3np94cHZwqivL1okoMFnIjqcAAzX5NOgd0VvM1dUqIwkXQDhp9IPGqDe/H1BiuRb8rmbJyRsxx5YjwksuPugDcG/B24qhyz4NM+gupMx0UE1DXS20xtE1kItEMzCyOJGXDwD9VR13ED0kYkcZoovPFdGFUOpAyAE9UYe1wDpDbmxF8o24tM5ICTcaATpiowWvBmS3i2qsEg8akpxmOqwWK//aOg2aNRiiX5we1H8QK8QNT0MoRf7B9bh59BHL6aOJ/jCeiYXb1jjWGQCGO9Vh3lzJWw2V9f2CvnUaZfeJOCzLgVPqtrI9E1LoPLiVT0Izx9DZ+aINrBxhNfndz5UZ4VQPHF8DDe4=
notifications:
  slack:
    secure: kq3GIlOS/TfZ4hk7z+Fw/cXLCbFEMy8olXIJGM8vRlRF1r/T0/XbSIkNugvV+NrR1rOKw9b8uiqNNo5YpjzWEpxxTOrPt2at90lVY6owQabbxApZHU8qK/aTBF0toJyDrNj+qdpUOKLlA88NJo6hvOkM+oX/mAsdvGmOkTs434ALdqgB0JnqOA1cKMYnFfMJSHee5lxcNnOly8w8BTJq6LYi9ST875IPUy4aqfTloF47guusp2Rko4BdDFGu4Q6qT1h4WWCr8IL7+4kDHCAyPeYYKEVOhBT3yxrkEMc8OtjtM7g2DMBcDOsFBGfN1MOca7TBtMcNE7ATEKkICohPPkF592mdbUkXjdQ01tQjL1ZN5Us6xIfWucuXTuBdChJfQcCAp2enDJx+S7zbihXxswyy0d5UWZJUNyKAnQY8XFSQ8cHMgngM/KHuKmM5+NSRaKe4oBpK2pGh2tAo+DOcKO6dQ7Y3fQ+/xjlhF66JrLSd++UDy7ix5D1xATIpzvBjNi6uciOn4LdeP68iYL7G9eIerFd9iEnw7cHnflnzFajmn2hWro2KJFqV5kN+YhgUzoRgvNhX0x9iAUGp5+d4qCfMkNgFphorD3UGDnVlfESA6hj1RWjKxpPf181sUFKz9apxiRsNKbYj1J7s8rUVIdvzWggZe8aByu16WGrVOMc=
